batch_type: numel
batch_bins: 7200000
# batch_type: unsorted
# batch_size: 2
accum_grad: 1
num_workers: 1
max_epoch: 200
patience: none
# dist_backend: nccl
# dist_world_size: 2
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10

init_param: [
    "/data/balaji/workdir3/espnet/egs2/librispeech/ssl1/exp/simpleoier/simpleoier_librispeech_hubert_iter1_train_ssl_torchaudiohubert_base_960h_pretrain_it1_raw/valid.loss.ave.pth:encoder:encoder"
]

input_size: 1
encoder: torchaudiohubert
encoder_conf:
    encoder_projection_dropout: 0.0
    encoder_attention_dropout: 0.0
    encoder_ff_interm_dropout: 0.1
    encoder_dropout: 0.0
    encoder_layer_drop: 0.05
    mask_prob: 0.65
    mask_channel_prob: 0.5
    mask_channel_length: 64
    num_classes: 500
    finetuning: true
    freeze_encoder_updates: 10000

decoder: transducer
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 256
    dropout: 0.1
    dropout_embed: 0.2

joint_net_conf:
    joint_space_size: 320

model_conf:
    ctc_weight: 0.3
    report_cer: False
    report_wer: False

optim: adam
optim_conf:
    lr: 0.00005
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 8000

unused_parameters: true

frontend: null

normalize: null

specaug: null