batch_type: numel
batch_bins: 9600000
# batch_type: unsorted
# batch_size: 2
accum_grad: 1
num_workers: 1
max_epoch: 200
patience: none
# dist_backend: nccl
# dist_world_size: 2
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 10

init_param: [
    "/data/balaji/workdir3/espnet/egs2/librispeech/ssl1/exp/simpleoier/simpleoier_librispeech_hubert_iter1_train_ssl_torchaudiohubert_base_960h_pretrain_it1_raw/valid.loss.ave.pth:encoder:encoder"
]

input_size: 1
encoder: torchaudiohubert
encoder_conf:
    encoder_projection_dropout: 0.0
    encoder_attention_dropout: 0.0
    encoder_ff_interm_dropout: 0.1
    encoder_dropout: 0.0
    encoder_layer_drop: 0.05
    mask_prob: 0.65
    mask_channel_prob: 0.5
    mask_channel_length: 64
    num_classes: 500
    finetuning: true
    freeze_encoder_updates: 10000

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.00005
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 8000

unused_parameters: true

frontend: null

normalize: null

specaug: null